site_name: Coronium SkyTable
pages:
  - 'Introduction': 'index.md'
  - 'Client Guide': 'guide.md'
  - 'Client Events': 'events.md'
  - 'Client API': 'api.md'
  - 'Server Guide': 'server.md'
  - 'Development Tips': 'development.md'
  - 'Example Setup': 'example.md'
  - 'About': 'about.md'
copyright: "&copy;2017 C. Byerley - develephant.com"
theme: readthedocs
site_url: https://develephant.github.io/coronium-skytable-docs
site_dir: ../docs
markdown_extensions:
  - admonition
  - codehilite