site_name: Coronium SkyTable
pages:
  - 'Introduction': 'index.md'
  - 'Server Install':
    - 'DigitalOcean': 'install/digitalocean.md'
    - 'Amazon EC2': 'install/ec2.md'
    - 'Quick Test': 'install/testing.md'
  - 'Server Guide':
    - 'Configuration': 'server/config.md'
    - 'Password': 'server/password.md'
    - 'Logs': 'server/logs.md'
    - 'System Service': 'server/system.md'
  - 'Client Guide': 'guide.md'
  - 'Client API': 'api.md'
  - 'Examples': 'example.md'
  - 'Demo': 'demo.md'
  - 'About': 'about.md'
copyright: "&copy;2017 C. Byerley - develephant.com"
theme: readthedocs
site_url: https://develephant.github.io/coronium-skytable-docs
site_dir: ../docs
markdown_extensions:
  - admonition
  - codehilite